### PR TITLE
Added support with Symfony Process 4.*

### PR DESCRIPTION
**Pull request by gquemener**

### CODE REVIEW

**Comment by gquemener** [comment]
Duplicate with https://github.com/mekras/php-speller/pull/7, the CI configuration should define a matrix running the tests against symfony process in version ^2.5, ^3.0 and ^4.0 to be more accurate.

**Comment by gquemener** [comment]
Here's an example of different symfony version requirements in Travis matrix: https://github.com/Behat/Behat/blob/master/.travis.yml

**Comment by repat** [comment]
@mekras any progress on this? we'd also need symfony processes in v4 :)

**Comment by icanhazstring** [comment]
Hi @all. Since I got added as collaborator I will look into this asap. There will probably some some updates according to new required packages. Thanks for your patience.

**Comment by icanhazstring** [comment]
Hi again. I just release v2.0 with support for symfony ^4.0.
Please see if this works for you, if not. Feel free to add another PR.

Closing this one.

**Pull request closed without merging**
